# Generated by Django 5.0.6 on 2024-05-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tie',
            field=models.BooleanField(default=False),
        ),
    ]
